---
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun build --compile ./main.ts --outfile pdsctl-linux-x86 --minify --bytecode
      - uses: actions/upload-artifact@v4
        with:
          name: pdsctl
          path: pdsctl-linux-x86
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: pdsctl-linux-x86
