---
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
      - run: bun build --compile ./main.ts --outfile pdsman-linux-x86 --minify --bytecode
      - uses: actions/upload-artifact@v4
        with:
          name: pdsman
          path: pdsman-linux-x86
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: pdsman-linux-x86
